<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            [
                'slug' => 'microblading',
                'sort_order' => 0,
                'name_tr' => 'Microblading', 'name_en' => 'Microblading',
                'tag_tr' => 'Kaş', 'tag_en' => 'Brows',
                'desc_tr' => 'Kıl tekniğiyle çizilen, gerçek kaşlardan ayırt edilemeyen doğal ve ince detaylı kaşlar.',
                'desc_en' => 'Hair-stroke technique that mimics natural brow hairs for a soft, undetectable finish.',
                'image' => '/images/micro.png',
                'seo_title_tr' => 'Microblading Ankara | Stria Studio',
                'seo_desc_tr' => "Ankara Çankaya'da microblading: kıl tekniğiyle doğal, kalıcı kaşlar. Steril ekipman, yüze özel tasarım. WhatsApp'tan randevu al.",
                'keywords_tr' => [
                    'microblading ankara',
                    'ankara microblading',
                    'kıl tekniği kaş',
                    'kalıcı kaş ankara',
                    'çankaya microblading',
                ],
                'intro_tr' => "Microblading, Ankara Çankaya'daki Stria Studio'da kıl tekniğiyle uygulanan yarı kalıcı bir kaş işlemidir. Her kıl tek tek çizilir; sonuç gerçek kaştan ayırt edilemeyecek kadar doğaldır ve 12–18 ay kalıcıdır.",
                'aftercare_tr' => 'İlk 7–10 gün kaşları ıslatmaktan, terlemekten ve güneşten koruyun; verilen bakım kremini uygulayın. Oluşan ince kabuklar kendiliğinden dökülür.',
                'benefits_tr' => [
                    'Gerçekçi kıl görünümü — makyajsız da dolgun kaş',
                    'Yüz simetrisine göre birebir tasarım ve ölçüm',
                    'Steril, tek kullanımlık iğne ve kaliteli pigment',
                    '12–18 ay kalıcılık, rötuş kontrolü dahil',
                ],
                'process_tr' => [
                    'Ücretsiz ön görüşme ve yüz analizi',
                    'Kaş tasarımı ve renk seçimi — onayınızla başlanır',
                    'Anestezik krem sonrası kıl kıl uygulama (~90 dakika)',
                    '4–6 hafta sonra rötuş seansı',
                ],
                'faq_tr' => [
                    ['q' => "Microblading Ankara'da ne kadar kalıcı?", 'a' => 'Cilt tipine bağlı olarak 12–18 ay kalıcıdır. Yıllık rötuşla görünüm korunur.'],
                    ['q' => 'İşlem acıtır mı?', 'a' => 'Uygulamadan önce anestezik krem sürülür; çoğu kişi yalnızca hafif bir kaşınma hisseder.'],
                    ['q' => 'Kimler microblading yaptıramaz?', 'a' => 'Hamileler, emzirenler, kan sulandırıcı kullananlar ve bazı cilt hastalığı olanlar uygun değildir; ön görüşmede değerlendirilir.'],
                ],
                'related' => ['kas-pudralama', 'kas-laminasyon'],
                'gallery' => [],
            ],
            [
                'slug' => 'kas-pudralama',
                'sort_order' => 1,
                'name_tr' => 'Kaş Pudralama', 'name_en' => 'Powder Brows',
                'tag_tr' => 'Kaş', 'tag_en' => 'Brows',
                'desc_tr' => 'Pudra dokusuyla dolgun, makyajlı bir kaş görünümü — yağlı ciltler için ideal.',
                'desc_en' => 'A soft, filled-in powdered look — ideal for oily skin and a made-up effect.',
                'image' => '/images/powder.png',
                'seo_title_tr' => 'Kaş Pudralama Ankara | Powder Brows',
                'seo_desc_tr' => "Ankara'da kaş pudralama (powder brows): pudra dokusuyla dolgun, makyajlı kaş. Yağlı ciltlere ideal, uzun ömürlü. Randevu için yazın.",
                'keywords_tr' => [
                    'kaş pudralama ankara',
                    'powder brows ankara',
                    'pudra kaş ankara',
                    'gölgeli kaş',
                ],
                'intro_tr' => "Kaş pudralama, Ankara Stria Studio'da kaşlara pudra makyajı etkisi veren yarı kalıcı bir tekniktir. Noktalama yöntemiyle uygulanan pigment dolgun, hafif gölgeli bir görünüm bırakır; yağlı ciltlerde microblading'e göre daha uzun ömürlüdür.",
                'aftercare_tr' => 'İlk 7–10 gün kaşları kuru tutun, güneş ve sauna gibi terleten ortamlardan kaçının, verilen kremi uygulayın.',
                'benefits_tr' => [
                    'Dolgun, makyajlı kaş görünümü',
                    'Yağlı ve karma ciltler için ideal',
                    "Microblading'e göre daha kalıcı sonuç",
                    'İyileşme sürecinde daha az hassasiyet',
                ],
                'process_tr' => [
                    'Ön görüşme ve cilt/kaş analizi',
                    'Kaş tasarımı ve renk yoğunluğu seçimi',
                    'Noktalama tekniğiyle uygulama (~90 dakika)',
                    '4–6 hafta sonra rötuş',
                ],
                'faq_tr' => [
                    ['q' => 'Kaş pudralama ne kadar kalıcı?', 'a' => 'Ortalama 1,5–2 yıl kalıcıdır; yağlı ciltte biraz daha kısa sürebilir.'],
                    ['q' => "Microblading'den farkı nedir?", 'a' => 'Microblading kıl kıl çizgiler yapar; pudralama pudra makyajı gibi dolgun bir gölge bırakır. Yağlı ciltlerde pudralama daha iyi tutar.'],
                    ['q' => 'İşlem sonrası kaşlar çok koyu mu olur?', 'a' => 'İlk günlerde renk koyu görünür, 7–10 günde gerçek tonuna açılır.'],
                ],
                'related' => ['microblading', 'kas-laminasyon'],
                'gallery' => [],
            ],
            [
                'slug' => 'eyeliner',
                'sort_order' => 2,
                'name_tr' => 'Eyeliner', 'name_en' => 'Eyeliner',
                'tag_tr' => 'Göz', 'tag_en' => 'Eyes',
                'desc_tr' => 'Bakışlarınızı belirginleştiren, kalıcı ve simetrik eyeliner uygulaması.',
                'desc_en' => 'A defined, symmetrical permanent eyeliner that opens up the gaze.',
                'image' => '/images/eyeliner.png',
                'seo_title_tr' => 'Kalıcı Eyeliner Ankara | Stria Studio',
                'seo_desc_tr' => "Ankara'da kalıcı eyeliner: simetrik, silinmeyen ince çizgi bakışları belirginleştirir. Steril, yüze özel uygulama. Randevu alın.",
                'keywords_tr' => [
                    'kalıcı eyeliner ankara',
                    'eyeliner ankara',
                    'kalıcı göz makyajı ankara',
                    'ankara kalıcı eyeliner',
                ],
                'intro_tr' => "Kalıcı eyeliner, Ankara Stria Studio'da kirpik hattına uygulanan silinmeyen ve simetrik bir göz makyajıdır. İnce ya da belirgin kalınlıkta yapılabilir, her sabah eyeliner çizme zahmetini ortadan kaldırır ve 1–3 yıl kalıcıdır.",
                'aftercare_tr' => 'İlk hafta gözü ovmaktan, makyajdan ve sudan koruyun; kaşınma olursa krem uygulayın, kabukları koparmayın.',
                'benefits_tr' => [
                    'Her sabah göz makyajı derdine son',
                    'İki gözde birebir simetri',
                    'İnce doğal ya da belirgin kalınlık seçeneği',
                    'Suya, tere ve gün boyu dayanıklı',
                ],
                'process_tr' => [
                    'Göz yapısı analizi ve kalınlık kararı',
                    'Anestezik krem uygulaması',
                    'Kirpik hattına pigment uygulama (~60–90 dakika)',
                    '4–6 hafta sonra rötuş',
                ],
                'faq_tr' => [
                    ['q' => 'Kalıcı eyeliner ne kadar kalıcı?', 'a' => '1–3 yıl arasında kalıcıdır; ince uygulamalar daha erken açılır.'],
                    ['q' => 'Lens kullanıyorum, sorun olur mu?', 'a' => 'İşlem sırasında lensler çıkarılır; iyileşene kadar birkaç gün gözlük önerilir.'],
                    ['q' => 'Doğal görünür mü?', 'a' => 'İsteğe göre kirpik dibinde ince ve doğal ya da belirgin çizgi yapılabilir.'],
                ],
                'related' => ['dipliner', 'microblading'],
                'gallery' => [],
            ],
            [
                'slug' => 'dipliner',
                'sort_order' => 3,
                'name_tr' => 'Dipliner', 'name_en' => 'Lash-line Enhancement',
                'tag_tr' => 'Göz', 'tag_en' => 'Eyes',
                'desc_tr' => 'Kirpik diplerine uygulanan ince pigment ile daha yoğun ve uyanık bir bakış.',
                'desc_en' => 'Fine pigment along the lash line for fuller lashes and a wide-awake look.',
                'image' => '/images/dipliner.png',
                'seo_title_tr' => 'Dipliner Ankara | Kirpik Dibi Dolgusu',
                'seo_desc_tr' => "Ankara'da dipliner: kirpik diplerine ince pigment ile daha yoğun, uyanık bakış. Doğal, fark edilmeyen kalıcı dokunuş. Randevu alın.",
                'keywords_tr' => [
                    'dipliner ankara',
                    'kirpik dibi dolgusu ankara',
                    'kirpik dibi pigment',
                    'doğal eyeliner ankara',
                ],
                'intro_tr' => "Dipliner, Ankara Stria Studio'da yalnızca kirpik diplerine uygulanan, eyeliner'a göre daha ince ve doğal bir kalıcı makyaj işlemidir. Kirpikleri daha sık ve dolgun gösterir; makyaj yapılmış izlenimi vermeden bakışları açar.",
                'aftercare_tr' => 'İlk hafta gözü sudan ve makyajdan koruyun, ovuşturmayın; oluşan ince kabukları kendiliğinden dökülmeye bırakın.',
                'benefits_tr' => [
                    'Kirpikler daha sık ve dolgun görünür',
                    'Çizgi belli olmadan doğal etki',
                    'Açık, uyanık bir bakış',
                    '1–3 yıl kalıcı',
                ],
                'process_tr' => [
                    'Kirpik hattı analizi',
                    'Anestezik krem uygulaması',
                    'Kirpik diplerine noktalı pigment (~60 dakika)',
                    '4–6 hafta sonra rötuş',
                ],
                'faq_tr' => [
                    ['q' => 'Dipliner ile eyeliner farkı nedir?', 'a' => 'Dipliner sadece kirpik diplerine uygulanır ve çizgi oluşturmaz; eyeliner ise görünür bir hat çizer.'],
                    ['q' => 'Ne kadar kalıcı?', 'a' => '1–3 yıl kalıcıdır; ince uygulama olduğu için zamanla doğal şekilde açılır.'],
                    ['q' => 'Acıtır mı?', 'a' => 'Anestezik krem sayesinde çoğu kişi yalnızca hafif bir his duyar.'],
                ],
                'related' => ['eyeliner', 'kirpik-lifting'],
                'gallery' => [],
            ],
            [
                'slug' => 'dudak-renklendirme',
                'sort_order' => 4,
                'name_tr' => 'Dudak Renklendirme', 'name_en' => 'Lip Blush',
                'tag_tr' => 'Dudak', 'tag_en' => 'Lips',
                'desc_tr' => 'Dudaklara doğal renk, tanım ve dolgunluk kazandıran kalıcı renklendirme.',
                'desc_en' => 'Restores natural colour, definition and fullness with a soft lip-blush tint.',
                'image' => '/images/dudak.png',
                'seo_title_tr' => 'Dudak Renklendirme Ankara | Lip Blush',
                'seo_desc_tr' => "Ankara'da dudak renklendirme (lip blush): dudaklara doğal renk, tanım ve dolgunluk. Solgun dudaklara canlılık. Randevu için yazın.",
                'keywords_tr' => [
                    'dudak renklendirme ankara',
                    'lip blush ankara',
                    'dudak pigmentasyonu ankara',
                    'kalıcı dudak rengi',
                ],
                'intro_tr' => "Dudak renklendirme (lip blush), Ankara Stria Studio'da dudaklara doğal renk, netlik ve dolgunluk kazandıran yarı kalıcı bir işlemdir. Soluk ya da sınırları belirsiz dudaklara sağlıklı bir canlılık verir; renk 1–2 yıl kalıcıdır.",
                'aftercare_tr' => 'İlk hafta dudakları nemli tutun, baharatlı-sıcak yiyeceklerden ve güneşten kaçının, kabukları koparmayın.',
                'benefits_tr' => [
                    'Dudaklara doğal, sağlıklı renk',
                    'Belirgin dudak sınırı ve dolgunluk hissi',
                    'Solgun ve açık tonlu dudaklara canlılık',
                    '1–2 yıl kalıcı',
                ],
                'process_tr' => [
                    'Ton ve dudak sınırı planlaması',
                    'Anestezik krem uygulaması',
                    'Pigment uygulama (~90 dakika)',
                    '4–6 hafta sonra rötuş',
                ],
                'faq_tr' => [
                    ['q' => 'Dudak renklendirme dudağı şişirir mi?', 'a' => 'Dolgu değildir; renk ve tanım verir. Hafif dolgunluk hissi görsel etkiden gelir.'],
                    ['q' => 'Ne kadar kalıcı?', 'a' => '1–2 yıl kalıcıdır; renk zamanla doğal şekilde açılır.'],
                    ['q' => 'Uçuk geçmişim var, yaptırabilir miyim?', 'a' => 'İşlem uçuğu tetikleyebilir; öncesinde doktor önerisiyle koruyucu tedavi gerekir.'],
                ],
                'related' => ['microblading', 'eyeliner'],
                'gallery' => [],
            ],
            [
                'slug' => 'kas-laminasyon',
                'sort_order' => 5,
                'name_tr' => 'Kaş Laminasyon', 'name_en' => 'Brow Lamination',
                'tag_tr' => 'Kaş', 'tag_en' => 'Brows',
                'desc_tr' => 'Kaş kıllarını şekillendirerek daha dolgun, bakımlı ve düzenli bir görünüm.',
                'desc_en' => 'Sets and lifts brow hairs for a fuller, groomed and lasting shape.',
                'image' => '/images/laminasyon.png',
                'seo_title_tr' => 'Kaş Laminasyonu Ankara | Brow Lamination',
                'seo_desc_tr' => "Ankara'da kaş laminasyonu: kaş kıllarını şekillendirip sabitler, dolgun ve bakımlı görünüm. İğnesiz, ~6 hafta etkili. Randevu alın.",
                'keywords_tr' => [
                    'kaş laminasyonu ankara',
                    'brow lamination ankara',
                    'kaş kaldırma ankara',
                    'kaş bakımı ankara',
                ],
                'intro_tr' => "Kaş laminasyonu, Ankara Stria Studio'da kaş kıllarını yukarı doğru şekillendirip sabitleyen iğnesiz bir bakım işlemidir. Seyrek ya da dağınık kaşları dolgun, düzenli ve bakımlı gösterir; etkisi yaklaşık 6 hafta sürer.",
                'aftercare_tr' => 'İlk 24 saat kaşları ıslatmayın ve dokunmayın; sonrasında düzenli olarak besleyici yağ uygulayın.',
                'benefits_tr' => [
                    'İğnesiz ve acısız uygulama',
                    'Dolgun, düzenli ve kaldırılmış kaş',
                    'Seyrek kaşları toparlar',
                    'Yaklaşık 6 hafta etki',
                ],
                'process_tr' => [
                    'Kaş analizi ve şekil planı',
                    'Kılları yumuşatma ve yukarı sabitleme',
                    'Besleyici bakım, isteğe bağlı renklendirme',
                    'Şekillendirme ve alma (~45–60 dakika)',
                ],
                'faq_tr' => [
                    ['q' => 'Kaş laminasyonu kalıcı mıdır?', 'a' => 'Kalıcı değildir; etkisi yaklaşık 6 hafta sürer, sonra kıllar eski haline döner.'],
                    ['q' => "Microblading'den farkı nedir?", 'a' => 'Microblading pigmentle kalıcı kaş çizer; laminasyon kendi kıllarınızı şekillendirir, boya veya iğne şart değildir.'],
                    ['q' => 'Kaşlara zarar verir mi?', 'a' => 'Doğru sürede ve besleyici bakımla uygulandığında zarar vermez.'],
                ],
                'related' => ['microblading', 'kas-pudralama'],
                'gallery' => [],
            ],
            [
                'slug' => 'kirpik-lifting',
                'sort_order' => 6,
                'name_tr' => 'Kirpik Lifting', 'name_en' => 'Lash Lift',
                'tag_tr' => 'Kirpik', 'tag_en' => 'Lashes',
                'desc_tr' => 'Kendi kirpiklerinizi kıvırarak uzatan, doğal ve kalıcı bir kirpik bakımı.',
                'desc_en' => 'Lifts and curls your own lashes for a longer, natural, low-maintenance look.',
                'image' => '/images/kirpik.png',
                'seo_title_tr' => 'Kirpik Lifting Ankara | Lash Lift',
                'seo_desc_tr' => "Ankara'da kirpik lifting (lash lift): kendi kirpiklerinizi kıvırıp uzun gösterir. Maskarasız açık bakış, ~6–8 hafta kalıcı. Randevu alın.",
                'keywords_tr' => [
                    'kirpik lifting ankara',
                    'lash lift ankara',
                    'kirpik kaldırma ankara',
                    'kirpik perması ankara',
                ],
                'intro_tr' => "Kirpik lifting (lash lift), Ankara Stria Studio'da kendi kirpiklerinizi dipten kıvırarak daha uzun ve dolgun gösteren bir işlemdir. Takma kirpik veya maskara olmadan açık, uyanık bir bakış verir; etkisi 6–8 hafta sürer.",
                'aftercare_tr' => 'İlk 24 saat kirpikleri ıslatmayın ve maskara sürmeyin; sonrasında besleyici kirpik serumu kullanabilirsiniz.',
                'benefits_tr' => [
                    'Kendi kirpikleriniz — takma kirpik yok',
                    'Maskarasız açık, uyanık bakış',
                    'Suya ve gün boyu dayanıklı',
                    'Yaklaşık 6–8 hafta kalıcı',
                ],
                'process_tr' => [
                    'Kirpik analizi ve kalıp seçimi',
                    'Lifting solüsyonuyla kıvırma',
                    'Besleme ve isteğe bağlı renklendirme',
                    'Uygulama (~45–60 dakika)',
                ],
                'faq_tr' => [
                    ['q' => 'Kirpik lifting ne kadar kalıcı?', 'a' => 'Kirpik büyüme döngüsüne göre 6–8 hafta kalıcıdır.'],
                    ['q' => 'Kirpiklere zarar verir mi?', 'a' => 'Uygun sürede ve besleyici bakımla uygulandığında zarar vermez.'],
                    ['q' => 'İşlemden sonra nelere dikkat etmeliyim?', 'a' => 'İlk 24 saat su ve buhardan kaçının; kirpikleri ovuşturmayın.'],
                ],
                'related' => ['dipliner', 'eyeliner'],
                'gallery' => [],
            ],
        ];

        foreach ($services as $s) {
            Service::updateOrCreate(['slug' => $s['slug']], $s + [
                'is_active' => true,
                'seo_title_en' => null,
                'seo_desc_en' => null,
                'keywords_en' => null,
                'intro_en' => null,
                'aftercare_en' => null,
                'benefits_en' => null,
                'process_en' => null,
                'faq_en' => null,
            ]);
        }
    }
}
