<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            [
                'slug' => 'microblading',
                'sort_order' => 0,
                'name_tr' => 'Microblading', 'name_en' => 'Microblading',
                'tag_tr' => 'Kaş', 'tag_en' => 'Brows',
                'desc_tr' => 'Kıl tekniğiyle çizilen, gerçek kaşlardan ayırt edilemeyen doğal ve ince detaylı kaşlar.',
                'desc_en' => 'Hair-stroke technique that mimics natural brow hairs for a soft, undetectable finish.',
                'image' => '/images/micro.png',
                'seo_title_tr' => 'Microblading Ankara | Kıl Tekniği Kaş',
                'seo_desc_tr' => "Ankara Çankaya'da microblading: kıl tekniğiyle doğal, kalıcı kaşlar. Steril ekipman, yüze özel tasarım. WhatsApp'tan randevu al.",
                'keywords_tr' => [
                    'microblading ankara',
                    'ankara microblading',
                    'kıl tekniği kaş',
                    'kaş microblading',
                    'kıl tekniği kaş ankara',
                    'kalıcı kaş ankara',
                    'çankaya microblading',
                ],
                'intro_tr' => "Microblading — halk arasında kıl tekniği kaş olarak bilinir — Ankara Çankaya'daki Stria Studio'da uygulanan yarı kalıcı bir kaş işlemidir. Her kıl tek tek çizilir; sonuç gerçek kaştan ayırt edilemeyecek kadar doğaldır ve 12–18 ay kalıcıdır.",
                'aftercare_tr' => 'İlk 7–10 gün kaşları ıslatmaktan, terlemekten ve güneşten koruyun; verilen bakım kremini uygulayın. Oluşan ince kabuklar kendiliğinden dökülür.',
                'benefits_tr' => [
                    'Gerçekçi kıl görünümü — makyajsız da dolgun kaş',
                    'Yüz simetrisine göre birebir tasarım ve ölçüm',
                    'Steril, tek kullanımlık iğne ve kaliteli pigment',
                    '12–18 ay kalıcılık, rötuş kontrolü dahil',
                ],
                'process_tr' => [
                    'Ücretsiz ön görüşme ve yüz analizi',
                    'Kaş tasarımı ve renk seçimi — onayınızla başlanır',
                    'Anestezik krem sonrası kıl kıl uygulama (~90 dakika)',
                    '4–6 hafta sonra rötuş seansı',
                ],
                'faq_tr' => [
                    ['q' => 'Kıl tekniği kaş nedir?', 'a' => "Kıl tekniği kaş, microblading işleminin halk arasındaki adıdır. Özel bir uçla cildin üst katmanına gerçek kıl görünümünde ince çizgiler işlenir; kaşlar doğal ve dolgun görünür. Yani kaş microblading, kıl tekniği kaş ve microblading aynı uygulamadır."],
                    ['q' => "Microblading Ankara'da ne kadar kalıcı?", 'a' => 'Cilt tipine bağlı olarak 12–18 ay kalıcıdır. Yıllık rötuşla görünüm korunur.'],
                    ['q' => 'İşlem acıtır mı?', 'a' => 'Uygulamadan önce anestezik krem sürülür; çoğu kişi yalnızca hafif bir kaşınma hisseder.'],
                    ['q' => 'Kimler microblading yaptıramaz?', 'a' => 'Hamileler, emzirenler, kan sulandırıcı kullananlar ve bazı cilt hastalığı olanlar uygun değildir; ön görüşmede değerlendirilir.'],
                ],
                'related' => ['kas-pudralama', 'kas-laminasyon'],
                'gallery' => [],
            ],
            [
                'slug' => 'kas-pudralama',
                'sort_order' => 1,
                'name_tr' => 'Kaş Pudralama', 'name_en' => 'Powder Brows',
                'tag_tr' => 'Kaş', 'tag_en' => 'Brows',
                'desc_tr' => 'Pudra dokusuyla dolgun, makyajlı bir kaş görünümü — yağlı ciltler için ideal.',
                'desc_en' => 'A soft, filled-in powdered look — ideal for oily skin and a made-up effect.',
                'image' => '/images/powder.png',
                'seo_title_tr' => 'Kaş Pudralama Ankara | Powder Brows',
                'seo_desc_tr' => "Ankara'da kaş pudralama (powder brows): pudra dokusuyla dolgun, makyajlı kaş. Yağlı ciltlere ideal, uzun ömürlü. Randevu için yazın.",
                'keywords_tr' => [
                    'kaş pudralama ankara',
                    'powder brows ankara',
                    'pudra kaş ankara',
                    'gölgeli kaş',
                ],
                'intro_tr' => "Kaş pudralama, Ankara Stria Studio'da kaşlara pudra makyajı etkisi veren yarı kalıcı bir tekniktir. Noktalama yöntemiyle uygulanan pigment dolgun, hafif gölgeli bir görünüm bırakır; yağlı ciltlerde microblading'e göre daha uzun ömürlüdür.",
                'aftercare_tr' => 'İlk 7–10 gün kaşları kuru tutun, güneş ve sauna gibi terleten ortamlardan kaçının, verilen kremi uygulayın.',
                'benefits_tr' => [
                    'Dolgun, makyajlı kaş görünümü',
                    'Yağlı ve karma ciltler için ideal',
                    "Microblading'e göre daha kalıcı sonuç",
                    'İyileşme sürecinde daha az hassasiyet',
                ],
                'process_tr' => [
                    'Ön görüşme ve cilt/kaş analizi',
                    'Kaş tasarımı ve renk yoğunluğu seçimi',
                    'Noktalama tekniğiyle uygulama (~90 dakika)',
                    '4–6 hafta sonra rötuş',
                ],
                'faq_tr' => [
                    ['q' => 'Kaş pudralama ne kadar kalıcı?', 'a' => 'Ortalama 1,5–2 yıl kalıcıdır; yağlı ciltte biraz daha kısa sürebilir.'],
                    ['q' => "Microblading'den farkı nedir?", 'a' => 'Microblading kıl kıl çizgiler yapar; pudralama pudra makyajı gibi dolgun bir gölge bırakır. Yağlı ciltlerde pudralama daha iyi tutar.'],
                    ['q' => 'İşlem sonrası kaşlar çok koyu mu olur?', 'a' => 'İlk günlerde renk koyu görünür, 7–10 günde gerçek tonuna açılır.'],
                ],
                'related' => ['microblading', 'kas-laminasyon'],
                'gallery' => [],
            ],
            [
                'slug' => 'eyeliner',
                'sort_order' => 2,
                'name_tr' => 'Eyeliner', 'name_en' => 'Eyeliner',
                'tag_tr' => 'Göz', 'tag_en' => 'Eyes',
                'desc_tr' => 'Bakışlarınızı belirginleştiren, kalıcı ve simetrik eyeliner uygulaması.',
                'desc_en' => 'A defined, symmetrical permanent eyeliner that opens up the gaze.',
                'image' => '/images/eyeliner.png',
                'seo_title_tr' => 'Kalıcı Eyeliner Ankara | Stria Studio',
                'seo_desc_tr' => "Ankara'da kalıcı eyeliner: simetrik, silinmeyen ince çizgi bakışları belirginleştirir. Steril, yüze özel uygulama. Randevu alın.",
                'keywords_tr' => [
                    'kalıcı eyeliner ankara',
                    'eyeliner ankara',
                    'kalıcı göz makyajı ankara',
                    'ankara kalıcı eyeliner',
                ],
                'intro_tr' => "Kalıcı eyeliner, Ankara Stria Studio'da kirpik hattına uygulanan silinmeyen ve simetrik bir göz makyajıdır. İnce ya da belirgin kalınlıkta yapılabilir, her sabah eyeliner çizme zahmetini ortadan kaldırır ve 1–3 yıl kalıcıdır.",
                'aftercare_tr' => 'İlk hafta gözü ovmaktan, makyajdan ve sudan koruyun; kaşınma olursa krem uygulayın, kabukları koparmayın.',
                'benefits_tr' => [
                    'Her sabah göz makyajı derdine son',
                    'İki gözde birebir simetri',
                    'İnce doğal ya da belirgin kalınlık seçeneği',
                    'Suya, tere ve gün boyu dayanıklı',
                ],
                'process_tr' => [
                    'Göz yapısı analizi ve kalınlık kararı',
                    'Anestezik krem uygulaması',
                    'Kirpik hattına pigment uygulama (~60–90 dakika)',
                    '4–6 hafta sonra rötuş',
                ],
                'faq_tr' => [
                    ['q' => 'Kalıcı eyeliner ne kadar kalıcı?', 'a' => '1–3 yıl arasında kalıcıdır; ince uygulamalar daha erken açılır.'],
                    ['q' => 'Lens kullanıyorum, sorun olur mu?', 'a' => 'İşlem sırasında lensler çıkarılır; iyileşene kadar birkaç gün gözlük önerilir.'],
                    ['q' => 'Doğal görünür mü?', 'a' => 'İsteğe göre kirpik dibinde ince ve doğal ya da belirgin çizgi yapılabilir.'],
                ],
                'related' => ['dipliner', 'microblading'],
                'gallery' => [],
            ],
            [
                'slug' => 'dipliner',
                'sort_order' => 3,
                'name_tr' => 'Dipliner', 'name_en' => 'Lash-line Enhancement',
                'tag_tr' => 'Göz', 'tag_en' => 'Eyes',
                'desc_tr' => 'Kirpik diplerine uygulanan ince pigment ile daha yoğun ve uyanık bir bakış.',
                'desc_en' => 'Fine pigment along the lash line for fuller lashes and a wide-awake look.',
                'image' => '/images/dipliner.png',
                'seo_title_tr' => 'Dipliner Ankara | Kirpik Dibi Dolgusu',
                'seo_desc_tr' => "Ankara'da dipliner: kirpik diplerine ince pigment ile daha yoğun, uyanık bakış. Doğal, fark edilmeyen kalıcı dokunuş. Randevu alın.",
                'keywords_tr' => [
                    'dipliner ankara',
                    'kirpik dibi dolgusu ankara',
                    'kirpik dibi pigment',
                    'doğal eyeliner ankara',
                ],
                'intro_tr' => "Dipliner, Ankara Stria Studio'da yalnızca kirpik diplerine uygulanan, eyeliner'a göre daha ince ve doğal bir kalıcı makyaj işlemidir. Kirpikleri daha sık ve dolgun gösterir; makyaj yapılmış izlenimi vermeden bakışları açar.",
                'aftercare_tr' => 'İlk hafta gözü sudan ve makyajdan koruyun, ovuşturmayın; oluşan ince kabukları kendiliğinden dökülmeye bırakın.',
                'benefits_tr' => [
                    'Kirpikler daha sık ve dolgun görünür',
                    'Çizgi belli olmadan doğal etki',
                    'Açık, uyanık bir bakış',
                    '1–3 yıl kalıcı',
                ],
                'process_tr' => [
                    'Kirpik hattı analizi',
                    'Anestezik krem uygulaması',
                    'Kirpik diplerine noktalı pigment (~60 dakika)',
                    '4–6 hafta sonra rötuş',
                ],
                'faq_tr' => [
                    ['q' => 'Dipliner ile eyeliner farkı nedir?', 'a' => 'Dipliner sadece kirpik diplerine uygulanır ve çizgi oluşturmaz; eyeliner ise görünür bir hat çizer.'],
                    ['q' => 'Ne kadar kalıcı?', 'a' => '1–3 yıl kalıcıdır; ince uygulama olduğu için zamanla doğal şekilde açılır.'],
                    ['q' => 'Acıtır mı?', 'a' => 'Anestezik krem sayesinde çoğu kişi yalnızca hafif bir his duyar.'],
                ],
                'related' => ['eyeliner', 'kirpik-lifting'],
                'gallery' => [],
            ],
            [
                'slug' => 'dudak-renklendirme',
                'sort_order' => 4,
                'name_tr' => 'Dudak Renklendirme', 'name_en' => 'Lip Blush',
                'tag_tr' => 'Dudak', 'tag_en' => 'Lips',
                'desc_tr' => 'Dudaklara doğal renk, tanım ve dolgunluk kazandıran kalıcı renklendirme.',
                'desc_en' => 'Restores natural colour, definition and fullness with a soft lip-blush tint.',
                'image' => '/images/dudak.png',
                'seo_title_tr' => 'Dudak Renklendirme Ankara | Lip Blush',
                'seo_desc_tr' => "Ankara'da dudak renklendirme (lip blush): dudaklara doğal renk, tanım ve dolgunluk. Solgun dudaklara canlılık. Randevu için yazın.",
                'keywords_tr' => [
                    'dudak renklendirme ankara',
                    'lip blush ankara',
                    'dudak pigmentasyonu ankara',
                    'kalıcı dudak rengi',
                ],
                'intro_tr' => "Dudak renklendirme (lip blush), Ankara Stria Studio'da dudaklara doğal renk, netlik ve dolgunluk kazandıran yarı kalıcı bir işlemdir. Soluk ya da sınırları belirsiz dudaklara sağlıklı bir canlılık verir; renk 1–2 yıl kalıcıdır.",
                'aftercare_tr' => 'İlk hafta dudakları nemli tutun, baharatlı-sıcak yiyeceklerden ve güneşten kaçının, kabukları koparmayın.',
                'benefits_tr' => [
                    'Dudaklara doğal, sağlıklı renk',
                    'Belirgin dudak sınırı ve dolgunluk hissi',
                    'Solgun ve açık tonlu dudaklara canlılık',
                    '1–2 yıl kalıcı',
                ],
                'process_tr' => [
                    'Ton ve dudak sınırı planlaması',
                    'Anestezik krem uygulaması',
                    'Pigment uygulama (~90 dakika)',
                    '4–6 hafta sonra rötuş',
                ],
                'faq_tr' => [
                    ['q' => 'Dudak renklendirme dudağı şişirir mi?', 'a' => 'Dolgu değildir; renk ve tanım verir. Hafif dolgunluk hissi görsel etkiden gelir.'],
                    ['q' => 'Ne kadar kalıcı?', 'a' => '1–2 yıl kalıcıdır; renk zamanla doğal şekilde açılır.'],
                    ['q' => 'Uçuk geçmişim var, yaptırabilir miyim?', 'a' => 'İşlem uçuğu tetikleyebilir; öncesinde doktor önerisiyle koruyucu tedavi gerekir.'],
                ],
                'related' => ['microblading', 'eyeliner'],
                'gallery' => [],
            ],
            [
                'slug' => 'kas-laminasyon',
                'sort_order' => 5,
                'name_tr' => 'Kaş Laminasyon', 'name_en' => 'Brow Lamination',
                'tag_tr' => 'Kaş', 'tag_en' => 'Brows',
                'desc_tr' => 'Kaş kıllarını şekillendirerek daha dolgun, bakımlı ve düzenli bir görünüm.',
                'desc_en' => 'Sets and lifts brow hairs for a fuller, groomed and lasting shape.',
                'image' => '/images/laminasyon.png',
                'seo_title_tr' => 'Kaş Laminasyonu Ankara | My Lamination Uzmanı',
                'seo_desc_tr' => "Ankara'da kaş laminasyonu: My Lamination ürünleriyle kaş kıllarını şekillendirip sabitler. İğnesiz, ~6 hafta etkili. Randevu alın.",
                'keywords_tr' => [
                    'kaş laminasyonu ankara',
                    'brow lamination ankara',
                    'kaş kaldırma ankara',
                    'kaş bakımı ankara',
                    'my lamination kaş laminasyonu',
                    'my lamination uzmanı ankara',
                    'my lamination ankara',
                ],
                'intro_tr' => "Kaş laminasyonu, Ankara Stria Studio'da kaş kıllarını yukarı doğru şekillendirip sabitleyen iğnesiz bir bakım işlemidir. Uygulamada My Lamination uzmanı olarak, İtalyan teknolojisiyle üretilen ve T.C. Sağlık Bakanlığı'na kayıtlı My Lamination ürünlerini kullanırız. Seyrek ya da dağınık kaşları dolgun, düzenli ve bakımlı gösterir; etkisi yaklaşık 6 hafta sürer.",
                'aftercare_tr' => 'İlk 24 saat kaşları ıslatmayın ve dokunmayın; sonrasında düzenli olarak besleyici yağ ya da My Lamination ev serumu uygulayın.',
                'benefits_tr' => [
                    'İğnesiz ve acısız uygulama',
                    'My Lamination ürünleriyle uygulama — vegan, paraben ve sülfat içermez',
                    'Dolgun, düzenli ve kaldırılmış kaş',
                    'Seyrek kaşları toparlar',
                    'Yaklaşık 6 hafta etki',
                ],
                'process_tr' => [
                    'Kaş analizi ve şekil planı',
                    'Cleansing Foam ile temizlik ve kıl hazırlığı',
                    'Lifting Cream ile kılları yumuşatma, Neutralising Cream ile yukarı sabitleme',
                    'Vitamin veya Mineral Lashbrow bakımı, isteğe bağlı renklendirme',
                    'Şekillendirme ve alma (~45–60 dakika)',
                ],
                'faq_tr' => [
                    ['q' => 'Kaş laminasyonu kalıcı mıdır?', 'a' => 'Kalıcı değildir; etkisi yaklaşık 6 hafta sürer, sonra kıllar eski haline döner.'],
                    ['q' => "Microblading'den farkı nedir?", 'a' => 'Microblading pigmentle kalıcı kaş çizer; laminasyon kendi kıllarınızı şekillendirir, boya veya iğne şart değildir.'],
                    ['q' => 'Kaşlara zarar verir mi?', 'a' => 'Doğru sürede ve besleyici bakımla uygulandığında zarar vermez. Kullandığımız My Lamination ürünleri vegan olup toksin, paraben ve sülfat içermez; formül kılı şekillendirirken vitamin ve mineral desteğiyle besler.'],
                    ['q' => 'Kaş laminasyonunda hangi ürünleri kullanıyorsunuz?', 'a' => "Stria Studio bir My Lamination uzmanıdır. Seansta Cleansing Foam ile temizlik, Lifting Cream ve Neutralising Cream ile şekillendirme, Vitamin veya Mineral Lashbrow ile bakım yaparız; renklendirmede PPD içermeyen My Lamination kaş boyasını Color Developer ile kullanırız. Ürünlerin tamamını My Lamination ürün rehberi sayfamızda anlattık."],
                    ['q' => 'My Lamination ürünleri neden tercih ediliyor?', 'a' => 'Ürünler İtalyan teknolojisiyle üretilir; Avrupa ve T.C. Sağlık Bakanlığı onaylıdır. Etkinliği İtalya\'daki Padua Üniversitesi laboratuvarlarında elektron mikroskobuyla ölçülmüş, işlem ve ev bakımı sonrası kıl çapında belirgin artış kaydedilmiştir.'],
                ],
                'related' => ['microblading', 'kas-pudralama'],
                'gallery' => [],
            ],
            [
                'slug' => 'kirpik-lifting',
                'sort_order' => 6,
                'name_tr' => 'Kirpik Lifting', 'name_en' => 'Lash Lift',
                'tag_tr' => 'Kirpik', 'tag_en' => 'Lashes',
                'desc_tr' => 'Kendi kirpiklerinizi kıvırarak uzatan, doğal ve kalıcı bir kirpik bakımı.',
                'desc_en' => 'Lifts and curls your own lashes for a longer, natural, low-maintenance look.',
                'image' => '/images/kirpik.png',
                'seo_title_tr' => 'Kirpik Lifting Ankara | My Lamination Uzmanı',
                'seo_desc_tr' => "Ankara'da kirpik lifting (lash lift): My Lamination ürünleriyle kendi kirpiklerinizi kıvırır. Maskarasız açık bakış, ~6–8 hafta kalıcı.",
                'keywords_tr' => [
                    'kirpik lifting ankara',
                    'lash lift ankara',
                    'kirpik kaldırma ankara',
                    'kirpik perması ankara',
                    'my lamination kirpik lifting',
                    'my lamination uzmanı ankara',
                    'kirpik laminasyonu ankara',
                ],
                'intro_tr' => "Kirpik lifting (lash lift), Ankara Stria Studio'da kendi kirpiklerinizi dipten kıvırarak daha uzun ve dolgun gösteren bir işlemdir. My Lamination uzmanı olarak, İtalyan teknolojisiyle üretilen ve T.C. Sağlık Bakanlığı'na kayıtlı My Lamination ürünlerini kullanırız. Takma kirpik veya maskara olmadan açık, uyanık bir bakış verir; etkisi 6–8 hafta sürer.",
                'aftercare_tr' => 'İlk 24 saat kirpikleri ıslatmayın ve maskara sürmeyin; sonrasında besleyici kirpik serumu (My Lamination Vitamin veya Mineral Serum Home) kullanabilirsiniz.',
                'benefits_tr' => [
                    'Kendi kirpikleriniz — takma kirpik yok',
                    'My Lamination ürünleriyle uygulama — vegan, paraben ve sülfat içermez',
                    'Maskarasız açık, uyanık bakış',
                    'Suya ve gün boyu dayanıklı',
                    'Yaklaşık 6–8 hafta kalıcı',
                ],
                'process_tr' => [
                    'Kirpik analizi ve silikon kalıp boyu seçimi',
                    'Temizlik, göz altı koruması ve kirpik sarma',
                    'Lifting Cream ile kıvırma, Neutralising Cream ile sabitleme',
                    'Vitamin veya Mineral Lashbrow bakımı, isteğe bağlı renklendirme',
                    'Hydrating Serum ile kapanış (~45–60 dakika)',
                ],
                'faq_tr' => [
                    ['q' => 'Kirpik lifting ne kadar kalıcı?', 'a' => 'Kirpik büyüme döngüsüne göre 6–8 hafta kalıcıdır.'],
                    ['q' => 'Kirpiklere zarar verir mi?', 'a' => 'Uygun sürede ve besleyici bakımla uygulandığında zarar vermez. Kullandığımız My Lamination solüsyonları vitamin ve mineral desteği içerir; toksin, paraben ve sülfat içermez.'],
                    ['q' => 'İşlemden sonra nelere dikkat etmeliyim?', 'a' => 'İlk 24 saat su ve buhardan kaçının; kirpikleri ovuşturmayın. Sonrasında günde iki kez kirpik serumu kullanmak sonucun daha iyi durmasını sağlar.'],
                    ['q' => 'Kirpik liftingde hangi ürünleri kullanıyorsunuz?', 'a' => "Stria Studio bir My Lamination uzmanıdır. Lifting Cream, Neutralising Cream ve Hydrating Serum üçlüsünü; kalıp ve fırçalarda Lamitta Shields, Lami Combo Pads ve Laminator Slide'ı kullanırız. Bakım için Vitamin ve Mineral Lashbrow kürlerini uygularız. Tüm ürünleri My Lamination ürün rehberi sayfamızda tek tek anlattık."],
                    ['q' => 'Kirpik lifting ile kirpik laminasyonu aynı şey mi?', 'a' => 'Pratikte aynı uygulamayı anlatır. Lifting kirpiği kıvırma işini, laminasyon ise bu işe eklenen vitamin ve mineral bakımını öne çıkarır. My Lamination protokolünde ikisi tek seansta birlikte yapılır.'],
                ],
                'related' => ['dipliner', 'eyeliner'],
                'gallery' => [],
            ],
            [
                'slug' => 'kamuflaj-makyaj',
                'sort_order' => 7,
                'name_tr' => 'Kamuflaj Makyaj', 'name_en' => 'Camouflage Makeup',
                'tag_tr' => 'Cilt', 'tag_en' => 'Skin',
                'desc_tr' => 'Çatlak, vitiligo, yanık ve ameliyat izlerini cilt tonunuza özel medikal pigmentlerle doğal görünüme kavuşturan kalıcı kamuflaj uygulaması.',
                'desc_en' => 'Permanent camouflage that blends stretch marks, vitiligo, burn and surgery scars into your natural skin tone with medical-grade pigments.',
                'image' => '/images/kamuflaj.png',
                'seo_title_tr' => 'Kamuflaj Makyaj Ankara | İz ve Leke Kapatma',
                'seo_desc_tr' => "Ankara'da kamuflaj makyaj: çatlak, vitiligo, yanık izi, ameliyat izi ve leke kapatma. Cilt tonuna özel medikal pigment, doğal ve kalıcı sonuç.",
                'keywords_tr' => [
                    'kamuflaj makyaj ankara',
                    'çatlak kapatma',
                    'vitiligo kamuflajı',
                    'yanık izi kapatma',
                    'ameliyat izi kapatma',
                    'leke kapatma',
                ],
                'intro_tr' => 'Kamuflaj makyaj; ciltteki iz, leke ve renk farklılıklarını cilt tonunuza özel hazırlanan medikal pigmentlerle kapatan yarı kalıcı bir uygulamadır. Konsültasyonda cildiniz değerlendirilir, renk analiziyle size özel pigment karışımı hazırlanır ve steril ortamda uygulanır. Sonuç doğaldır; suya ve tere dayanıklıdır.',
                'aftercare_tr' => 'İlk 14 gün bölgeyi güneşten koruyun, peeling ve asitli ürünlerden kaçının. Renk 4-6 haftada tam oturur; gerekli görülürse rötuş seansı planlanır.',
                'benefits_tr' => [
                    'Cilt tonuna özel pigment karışımı — çevre ciltle tam uyum',
                    'Vitiligo, yanık ve derin izlerde dahi yüksek kapatma gücü',
                    'Suya ve tere dayanıklı, uzun ömürlü sonuç',
                    'REACH ve CE uyumlu, dermatolojik test edilmiş pigmentler',
                    'Kadın, erkek ve her cilt tipine uygulanabilir',
                ],
                'process_tr' => [
                    'Konsültasyon — Cilt tipiniz, iz veya leke yapınız ve beklentiniz değerlendirilir.',
                    'Renk Analizi — Cildinizin ton ve alt tonu ölçülerek size özel pigment karışımı hazırlanır; test uygulaması yapılır.',
                    'Uygulama — Steril, tek kullanımlık ekipmanla pigment cildin üst katmanına işlenir; bölgeye göre 1-3 saat sürer.',
                    'İyileşme ve Rötuş — Renk 4-6 haftada oturur; kontrol seansında sonuç kalıcı hâle getirilir.',
                ],
                'faq_tr' => [
                    ['q' => 'Kamuflaj makyaj nedir?', 'a' => 'Ciltteki iz, leke ve renk farklılıklarını cilt tonunuza uyumlu medikal pigmentlerle kapatan yarı kalıcı bir medikal estetik uygulamasıdır.'],
                    ['q' => 'Hangi izlere uygulanır?', 'a' => 'Çatlak, vitiligo, yanık izi, ameliyat ve sezaryen izi, doğum lekesi, sivilce izi, dövme, rosacea, güneş lekesi ve kılcal damar görünümü dahil pek çok cilt sorununa uygulanır.'],
                    ['q' => 'Sonuç ne kadar kalıcı?', 'a' => 'Kullanılan pigmente ve cilt yapısına göre uzun yıllar kalıcıdır; periyodik rötuşlarla ömrü uzatılabilir.'],
                    ['q' => 'Uygulama ağrılı mı?', 'a' => 'Genellikle ağrısızdır; gerekli durumlarda anestezik krem kullanılarak konfor sağlanır.'],
                    ['q' => 'Kimlere uygulanmaz?', 'a' => 'Aktif cilt enfeksiyonu olanlar, gebelik/emzirme dönemindekiler ve iyileşmeyi etkileyen kronik rahatsızlığı olanlar için ön görüşmede değerlendirme yapılır.'],
                ],
                'subservices_tr' => [
                    [
                        'slug' => 'catlak-gizleme',
                        'gallery' => ['/images/works/catlak-gizleme-1.png', '/images/works/catlak-gizleme-2.png'],
                        'name' => 'Çatlak Gizleme',
                        'desc' => 'Hamilelik, kilo değişimi ve büyüme dönemine bağlı çatlaklar cilt tonunuza özel medikal pigmentlerle kalıcı olarak kamufle edilir.',
                        'seo_title' => 'Çatlak Gizleme Ankara | Doğal Cilt Tonu',
                        'seo_desc' => "Ankara'da çatlak gizleme uygulamasıyla renk farkını cilt tonunuza özel pigmentlerle kamufle edin. Stria Studio'da ön görüşme için hemen iletişime geçin.",
                        'intro' => "Çatlak gizleme, ciltteki açık renkli çatlak çizgileri ile çevre doku arasındaki ton farkını azaltmayı amaçlayan bir kamuflaj uygulamasıdır. Özellikle rengi oturmuş, hipopigmente çatlakların daha bütünlüklü ve doğal görünmesine yardımcı olur.\n\nStria Studio'da önce çatlağın dokusu ve cildin alt tonu incelenir. Kişiye özel hazırlanan medikal pigment, steril ve tek kullanımlık ekipmanla kontrollü katmanlar hâlinde uygulanır; iyileşme sonrasında renk uyumu yeniden değerlendirilir.",
                        'benefits' => [
                            'Açık renkli çatlaklarla çevre cilt arasındaki kontrastı azaltır',
                            'Karın, kalça, basen ve bacak bölgelerine uyarlanabilir',
                            'Cildin alt tonuna göre kişisel pigment karışımı hazırlanır',
                            'Makyajla günlük kapatma ihtiyacını azaltmaya yardımcı olur',
                        ],
                        'faq' => [
                            ['q' => 'Çatlak gizleme kaç seans sürer?', 'a' => 'Çatlağın genişliği, rengi ve cildin pigmenti tutma biçimine göre genellikle birden fazla seans planlanabilir; net plan ön görüşmede oluşturulur.'],
                            ['q' => 'Yeni ve kırmızı çatlaklara uygulanır mı?', 'a' => 'Kamuflaj için çoğunlukla rengi oturmuş, açık tonlu çatlaklar tercih edilir. Yeni veya aktif görünümlü çatlakların önce olgunlaşması beklenebilir.'],
                            ['q' => 'İyileşirken renk nasıl görünür?', 'a' => 'İlk günlerde pigment daha koyu veya sıcak görünebilir. Kabuklanma azaldıkça ton yumuşar ve nihai uyum birkaç hafta içinde değerlendirilir.'],
                            ['q' => 'Sonuç doğal görünür mü?', 'a' => 'Amaç çatlağın dokusunu yok etmek değil, renk farkını azaltmaktır. Doğallık; doğru alt ton seçimi ve kontrollü pigment katmanlarıyla desteklenir.'],
                        ],
                    ],
                    [
                        'slug' => 'vitiligo-kamuflaji',
                        'gallery' => ['/images/works/vitiligo-kamuflaji-1.png', '/images/works/vitiligo-kamuflaji-2.png'],
                        'name' => 'Vitiligo Kamuflajı',
                        'desc' => 'Yüz, el, kol ve vücuttaki vitiligo lekeleri cilt tonuyla tam uyumlu pigmentlerle homojen bir görünüme kavuşturulur.',
                        'seo_title' => 'Vitiligo Kamuflajı Ankara | Ton Eşitleme',
                        'seo_desc' => "Ankara'da vitiligo kamuflajı ile depigmente alanların görünümünü ten renginize özel pigmentlerle dengeleyin. Uygunluk görüşmesi için şimdi bize ulaşın.",
                        'intro' => "Vitiligo kamuflajı, melanin kaybı nedeniyle oluşan depigmente alanlarla çevredeki cilt arasındaki belirgin renk ayrımını optik olarak yumuşatır. Uygulama vitiligoyu tedavi etmez; stabil beyaz alanların ten rengine daha yakın görünmesini hedefler.\n\nStria Studio süreci lekenin stabilitesi, bölgesi ve güneş görme alışkanlığının değerlendirilmesiyle başlar. Alt ton analizi sonrası hazırlanan medikal pigment küçük bir alanda denenir; uyum gözlendikten sonra steril ekipmanla kademeli uygulamaya geçilir.",
                        'benefits' => [
                            'Depigmente alanların keskin sınırlarını görsel olarak yumuşatır',
                            'Yüz, el, kol ve vücudun uygun bölgeleri için planlanabilir',
                            'Tenin mevsimsel renk değişimi dikkate alınarak ton seçilir',
                            'Günlük kapatıcı kullanımına pratik bir alternatif sunar',
                        ],
                        'faq' => [
                            ['q' => 'Vitiligo kamuflajı aktif vitiligoya yapılır mı?', 'a' => 'Yeni lekelerin oluştuğu veya mevcut alanların büyüdüğü aktif dönemde uygulama ertelenebilir. Stabilite ve uygunluk ön görüşmede değerlendirilir.'],
                            ['q' => 'El ve parmaklarda pigment kalıcılığı aynı mıdır?', 'a' => 'Eller sık yıkama, sürtünme ve güneşe maruz kaldığı için pigmenti diğer bölgelere göre daha hızlı açabilir; rötuş ihtiyacı değişebilir.'],
                            ['q' => 'Kaç seans gerekir?', 'a' => 'Alan büyüklüğü, yerleşimi ve hedeflenen ton yoğunluğu seans sayısını belirler. Pigmentin iyileşmiş rengi görüldükten sonra ek seans kararı verilir.'],
                            ['q' => 'Kamuflaj sonrasında güneşlenebilir miyim?', 'a' => 'Pigmentli alan bronzlaşmazken çevre cilt koyulaşabilir ve renk farkı yeniden belirginleşebilir. Düzenli yüksek korumalı güneş ürünü kullanılması önemlidir.'],
                        ],
                    ],
                    [
                        'slug' => 'yanik-izi-kapatma',
                        'gallery' => ['/images/works/yanik-izi-kapatma-1.png', '/images/works/yanik-izi-kapatma-2.png'],
                        'name' => 'Yanık İzi Kapatma',
                        'desc' => 'Termal, kimyasal veya elektriksel yanık izleri ve renk farklılıkları doğal cilt tonuna yaklaştırılır.',
                        'seo_title' => 'Yanık İzi Kapatma Ankara | Doğal Kamuflaj',
                        'seo_desc' => "Ankara'da yanık izi kapatma ile iyileşmiş izlerdeki renk farklılığını kişisel pigment eşleştirmesiyle kamufle edin. Değerlendirme için hemen randevu alın.",
                        'intro' => "Yanık izi kapatma, termal, kimyasal veya elektriksel yanık sonrasında tamamen iyileşmiş dokuda kalan açık renkli alanları çevre cilde yaklaştırmayı amaçlar. Kabarık, aktif ya da hassas izi ortadan kaldırmaz; yalnızca uygun izlerdeki pigment farkını kamufle eder.\n\nStria Studio'da iz dokusunun olgunluğu ve yüzey yapısı dikkatle incelenir. Cilt rengine göre birkaç pigment tonu hazırlanıp test edilir; seçilen medikal pigment steril koşullarda düşük yoğunlukla işlenerek rengin aşamalı ve kontrollü biçimde oluşması sağlanır.",
                        'benefits' => [
                            'İyileşmiş yanık alanındaki açık renk kontrastını azaltır',
                            'Düzensiz sınırlara noktasal ve kontrollü renk geçişi sağlar',
                            'İzin çevresindeki sağlam cilt tonuna özel eşleştirme yapılır',
                            'Giyimle kapatma veya bölgesel makyaj ihtiyacını azaltabilir',
                        ],
                        'faq' => [
                            ['q' => 'Her yanık izine pigment uygulanabilir mi?', 'a' => 'Hayır. Açık yara, aktif kızarıklık, kabarık keloid eğilimi veya iyileşmesi tamamlanmamış doku uygulama için uygun olmayabilir.'],
                            ['q' => 'Yanığın üzerinden ne kadar zaman geçmeli?', 'a' => 'İzin renginin ve dokusunun tamamen sakinleşmesi gerekir. Süre kişiye ve yanığın niteliğine göre değiştiğinden değerlendirme iyileşme sonrasında yapılır.'],
                            ['q' => 'Uygulama sırasında rahatsızlık olur mu?', 'a' => 'Yanık dokusunda his artabilir veya azalabilir. Konfor yaklaşımı bölgenin duyarlılığına göre belirlenir ve işlem boyunca cilt tepkisi izlenir.'],
                            ['q' => 'Doku çukurluğu da kapanır mı?', 'a' => 'Pigment uygulaması renk farkını hedefler; kabarıklık veya çöküklük gibi doku farklılıklarını gidermez. Görsel sonuç mevcut yüzey yapısına bağlıdır.'],
                        ],
                    ],
                    [
                        'slug' => 'ameliyat-izi-kapatma',
                        'gallery' => ['/images/works/ameliyat-izi-kapatma-1.png', '/images/works/ameliyat-izi-kapatma-2.png'],
                        'name' => 'Ameliyat İzi Kapatma',
                        'desc' => 'Estetik, ortopedi ve genel cerrahi sonrası kalan izler fark edilmeyecek şekilde kamufle edilir.',
                        'seo_title' => 'Ameliyat İzi Kapatma Ankara | İz Kamuflajı',
                        'seo_desc' => "Ankara'da ameliyat izi kapatma ile iyileşmiş cerrahi izlerin ton farkını cildinize özel pigmentlerle azaltın. Kişisel değerlendirme için hemen bize yazın.",
                        'intro' => "Ameliyat izi kapatma, estetik, ortopedi veya genel cerrahi sonrasında kalan ve çevre deriden daha açık görünen insizyon hatlarını renk açısından kamufle eder. Uygulama izin yapısını değiştirmez; olgunlaşmış, düz ve stabil cerrahi izlerin daha az dikkat çekmesini amaçlar.\n\nStria Studio'da operasyon geçmişi ve izin iyileşme durumu konuşulduktan sonra çevre ciltten renk örnekleri alınır. Alt tona uygun medikal pigment karışımı önce test edilir, ardından steril tek kullanımlık uçlarla ince insizyon hattı boyunca ölçülü biçimde uygulanır.",
                        'benefits' => [
                            'İnce cerrahi hat ile çevre cilt arasındaki renk ayrımını azaltır',
                            'Farklı operasyon bölgelerine göre hassas çalışma planı sunar',
                            'İzin sınırlarında yumuşak ve kademeli ton geçişi oluşturur',
                            'Ten rengine göre birden fazla pigment tonunu birleştirir',
                        ],
                        'faq' => [
                            ['q' => 'Ameliyat izine ne zaman kamuflaj yapılabilir?', 'a' => 'İzin tamamen kapanmış, yumuşamış ve renginin stabil hâle gelmiş olması beklenir. Cerrahınızın önerileri ve doku durumu değerlendirmede dikkate alınır.'],
                            ['q' => 'Kabarık ameliyat izleri uygun mudur?', 'a' => 'Kabarık, kızarık, kaşıntılı veya keloid eğilimli izler pigment için uygun olmayabilir. Uygulama yalnızca elverişli, iyileşmiş dokuda planlanır.'],
                            ['q' => 'İnce bir iz için kaç seans gerekir?', 'a' => 'İzin uzunluğu, alt tonu ve pigmenti kabul etmesi belirleyicidir. İlk uygulama iyileştikten sonra renk boşlukları için rötuş planlanabilir.'],
                            ['q' => 'Pigment izin tamamını görünmez yapar mı?', 'a' => 'Hayır. Hedef izin rengini çevre cilde yaklaştırmaktır; ışıkta görülen yüzey ve doku farkı tamamen kaybolmayabilir.'],
                        ],
                    ],
                    [
                        'slug' => 'yara-izi-kapatma',
                        'gallery' => ['/images/works/yara-izi-kapatma-1.png', '/images/works/yara-izi-kapatma-2.png'],
                        'name' => 'Yara İzi Kapatma',
                        'desc' => 'Kaza, kesik ve travma sonrası kalan izler medikal pigmentlerle gizlenir.',
                        'seo_title' => 'Yara İzi Kapatma Ankara | Dengeli Cilt Tonu',
                        'seo_desc' => "Ankara'da yara izi kapatma ile kaza, kesik ve travma sonrası kalan açık renkli izleri teninize özel pigmentlerle kamufle edin. Görüşme için bize ulaşın.",
                        'intro' => "Yara izi kapatma, kaza, kesik veya travma sonrasında iyileşen deride kalan hipopigmentasyonu çevredeki ten rengine yaklaştıran bir yöntemdir. Düz ve rengi oturmuş izlerde görsel bütünlük hedeflenir; pigment uygulaması yara dokusunu onarmaz ya da yüzey farklılığını ortadan kaldırmaz.\n\nStria Studio'daki görüşmede izin yaşı, derinliği, rengi ve bulunduğu bölgenin hareketi birlikte değerlendirilir. Çevre deriye uyan medikal pigmentler karıştırılır; küçük renk denemesinden sonra steril ekipmanla izin biçimine göre noktasal veya çizgisel çalışma yapılır.",
                        'benefits' => [
                            'Kesik ve travma izlerindeki açık renk görünümünü yumuşatır',
                            'Düz, çizgisel ya da düzensiz iz şekline göre uygulanabilir',
                            'Hareketli bölgelerde çalışma yoğunluğu özel olarak planlanır',
                            'Çevre tenle uyum için ara pigment tonları hazırlanır',
                        ],
                        'faq' => [
                            ['q' => 'Eski yara izleri kamuflaja uygun mudur?', 'a' => 'Tamamen iyileşmiş ve rengi stabil eski izler değerlendirmeye uygundur. Doku kabarıksa, hassassa veya renk değişimi sürüyorsa uygulama ertelenebilir.'],
                            ['q' => 'Yüzdeki kesik izine uygulanabilir mi?', 'a' => 'Yüzdeki uygun izlerde hassas bir plan yapılabilir. Renk eşleştirmesinde yüzün güneş görme düzeyi ve doğal ton geçişleri dikkate alınır.'],
                            ['q' => 'İyileşme döneminde nelere dikkat edilir?', 'a' => 'Bölge temiz tutulur; kabuklar koparılmaz, sürtünme ve güneşten korunur. Verilen bakım önerileri pigmentin dengeli oturmasına yardımcı olur.'],
                            ['q' => 'Rötuş neden gerekebilir?', 'a' => 'Skar dokusu pigmenti normal ciltten farklı tutabilir. İyileşme sonrası açık kalan noktaları dengelemek veya tonu yumuşatmak için rötuş yapılabilir.'],
                        ],
                    ],
                    [
                        'slug' => 'sezaryen-izi-kapatma',
                        'gallery' => ['/images/works/sezaryen-izi-kapatma-1.png', '/images/works/sezaryen-izi-kapatma-2.png'],
                        'name' => 'Sezaryen İzi Kapatma',
                        'desc' => 'Sezaryen sonrası karın bölgesindeki iz, cilt tonuna uyumlu pigmentlerle doğal görünüme kavuşturulur.',
                        'seo_title' => 'Sezaryen İzi Kapatma Ankara | Doğal Görünüm',
                        'seo_desc' => "Ankara'da sezaryen izi kapatma ile iyileşmiş insizyon hattının renk farkını teninize özel pigmentlerle kamufle edin. Ön değerlendirme için randevu alın.",
                        'intro' => "Sezaryen izi kapatma, alt karın bölgesindeki tamamen iyileşmiş insizyon hattı çevre ciltten daha açık kaldığında renk farkını azaltmak için uygulanır. Pigment, sezaryen izinin dokusunu veya kabarıklığını değiştirmez; düz ve olgunlaşmış hattın tenle daha uyumlu görünmesini destekler.\n\nStria Studio'da doğumdan sonra geçen süre, izin hassasiyeti ve karın bölgesinin alt tonu incelenir. Doğal cilt kıvrımları gözetilerek medikal pigment karışımı hazırlanır ve test edilir; uygun ton steril ekipmanla ince hat boyunca kontrollü biçimde yerleştirilir.",
                        'benefits' => [
                            'Alt karındaki açık insizyon hattının belirginliğini azaltır',
                            'İnce ve yatay iz yapısına göre hassas pigmentleme sağlar',
                            'Karın cildinin alt tonu ve doğal gölgeleriyle eşleştirilir',
                            'Bikini bölgesinde daha bütünlüklü bir ton görünümü sunar',
                        ],
                        'faq' => [
                            ['q' => 'Doğumdan ne kadar sonra uygulanabilir?', 'a' => 'İzin tamamen kapanması, sertliğinin azalması ve renginin stabil hâle gelmesi beklenir. Kişisel iyileşme süresi farklı olduğundan erken dönemde işlem yapılmaz.'],
                            ['q' => 'Emzirme döneminde yapılır mı?', 'a' => 'Gebelik ve emzirme döneminde uygulama ertelenir. Uygun zamanlama, kişisel durum ve stüdyo protokolü ön görüşmede açıklanır.'],
                            ['q' => 'Sezaryen izi kabarıksa kapatılabilir mi?', 'a' => 'Pigment kabarıklığı düzleştirmez. Kırmızı, hassas, kaşıntılı veya keloid yapıdaki izler için önce uzman hekim değerlendirmesi gerekebilir.'],
                            ['q' => 'İşlemden sonra kıyafet seçimi önemli mi?', 'a' => 'İlk günlerde bölgeyi sıkan ve sürten giysilerden kaçınmak rahatlık sağlar. Bakım süresince bölge temiz, kuru ve güneşten korunmuş tutulur.'],
                        ],
                    ],
                    [
                        'slug' => 'dogum-lekesi-kapatma',
                        'gallery' => ['/images/works/dogum-lekesi-kapatma-1.png', '/images/works/dogum-lekesi-kapatma-2.png'],
                        'name' => 'Doğum Lekesi Kapatma',
                        'desc' => 'Doğuştan gelen kahverengi ve sütlü kahve (café-au-lait) lekeleri çevre ciltle eşitlenir.',
                        'seo_title' => 'Doğum Lekesi Kapatma Ankara | Ton Eşitleme',
                        'seo_desc' => "Ankara'da doğum lekesi kapatma ile café-au-lait gibi renk farklılıklarını cilt tonunuza uygun pigmentlerle kamufle edin. Uygunluk görüşmesi için yazın.",
                        'intro' => "Doğum lekesi kapatma, café-au-lait gibi doğuştan gelen ve çevre deriden farklı renkte görünen stabil alanların kontrastını kamuflaj yoluyla azaltmayı amaçlar. Lekenin yapısını değiştirmez; uygun yüzeylerde çevredeki cilt tonuna daha dengeli bir görünüm kazandırır.\n\nStria Studio'da lekenin rengi, sınırları, büyüklüğü ve güneşe verdiği tepki ele alınır. Gerekli dermatolojik kontroller tamamlandıktan sonra çevre cilt için ayrıntılı renk analizi yapılır; medikal pigment test alanında gözlenir ve steril uygulama aşamalar hâlinde ilerletilir.",
                        'benefits' => [
                            'Café-au-lait lekelerinde çevre ciltle olan kontrastı yumuşatır',
                            'Geniş veya düzensiz sınırlı alanlarda kademeli geçiş sağlar',
                            'Lekenin bulunduğu bölgenin doğal ton değişimlerini gözetir',
                            'Günlük yüksek kapatıcılı makyaj ihtiyacını azaltabilir',
                        ],
                        'faq' => [
                            ['q' => 'Her doğum lekesi kamufle edilebilir mi?', 'a' => 'Hayır. Lekenin türü, yüzeyi ve değişim öyküsü önemlidir. Yeni büyüme, şekil veya renk değişikliği varsa pigment öncesinde dermatoloji değerlendirmesi gerekir.'],
                            ['q' => 'Café-au-lait lekesinde kaç seans gerekir?', 'a' => 'Lekenin koyuluğu, genişliği ve pigmentin iyileşmiş tonu seans planını belirler. Geniş alanlar kontrollü yoğunluk için aşamalara ayrılabilir.'],
                            ['q' => 'Leke güneşte koyulaşırsa ne olur?', 'a' => 'Doğal pigment değişirken kamuflaj pigmenti aynı hızda değişmez; mevsimsel ton farkı oluşabilir. Güneş koruması renk uyumunu korumaya yardımcıdır.'],
                            ['q' => 'Uygulama çocuklara yapılır mı?', 'a' => 'Kalıcı makyaj niteliğindeki bu işlem yetişkinler için değerlendirilir. Reşit olmayanlar için uygulama planlanmaz.'],
                        ],
                    ],
                    [
                        'slug' => 'leke-pigment-kamuflaji',
                        'gallery' => ['/images/works/leke-pigment-kamuflaji-1.png', '/images/works/leke-pigment-kamuflaji-2.png'],
                        'name' => 'Leke & Pigment Kamuflajı',
                        'desc' => 'Melasma, hiperpigmentasyon ve ton eşitsizlikleri homojen bir görünüme dönüştürülür.',
                        'seo_title' => 'Leke & Pigment Kamuflajı Ankara | Eşit Ton',
                        'seo_desc' => "Ankara'da leke & pigment kamuflajı ile uygun ton eşitsizliklerinin görünümünü kişisel renk analiziyle dengeleyin. Bilgi ve randevu için hemen bize ulaşın.",
                        'intro' => "Leke ve pigment kamuflajı, ciltteki lokal ton eşitsizliklerini çevre renge yaklaştırmayı hedefleyen optik bir uygulamadır. Melasma ve hiperpigmentasyon aktif biçimde değişebildiği için her koyu leke pigmentlemeye uygun değildir; işlem tedavi yerine yalnızca seçilmiş, stabil alanlarda görünümü dengelemeyi amaçlar.\n\nStria Studio değerlendirmesinde lekenin kaynağı, derinliği ve son dönemde değişip değişmediği sorgulanır. Uygunluk sağlanırsa cilt alt tonu ölçülür, medikal pigment denemesi yapılır ve steril uygulama küçük bölümler hâlinde ilerletilerek aşırı renk yüklemesinden kaçınılır.",
                        'benefits' => [
                            'Seçilmiş stabil renk eşitsizliklerinde sınır kontrastını azaltır',
                            'Soğuk, sıcak ve nötr alt tonlara özel renk karışımı sunar',
                            'Küçük ve lokal alanlarda hedefli çalışma olanağı sağlar',
                            'Yoğun kapatıcıyla günlük ton eşitleme ihtiyacını hafifletebilir',
                        ],
                        'faq' => [
                            ['q' => 'Melasma pigmentle kapatılabilir mi?', 'a' => 'Melasma hormonlar ve güneşle değişebildiği için çoğu durumda dikkatli değerlendirilir ve uygun bulunmayabilir. Öncelik lekenin stabil olduğunun anlaşılmasıdır.'],
                            ['q' => 'Koyu lekeye açık pigment uygulamak doğal görünür mü?', 'a' => 'Tek kat açık renk kullanmak gri veya yapay sonuç oluşturabilir. Uygun adaylarda renk düzeltme ve katmanlama, cildin alt tonuna göre planlanır.'],
                            ['q' => 'Kimlere uygulanmaz?', 'a' => 'Tanısı konmamış, büyüyen, kabuklanan ya da renk değiştiren lekelerde işlem yapılmaz. Aktif cilt hastalığı olan bölgeler de uygun değildir.'],
                            ['q' => 'Sonuç ne zaman değerlendirilir?', 'a' => 'İlk renk gerçek sonucu göstermez. Pigment yerleştikten ve yüzey iyileştikten birkaç hafta sonra ton uyumu değerlendirilerek gerekirse yeni plan yapılır.'],
                        ],
                    ],
                    [
                        'slug' => 'sivilce-izi-kapatma',
                        'gallery' => ['/images/works/sivilce-izi-kapatma-1.png', '/images/works/sivilce-izi-kapatma-2.png'],
                        'name' => 'Sivilce İzi Kapatma',
                        'desc' => 'Akne sonrası kalan renk farklılıkları ve yüzeysel izler pürüzsüz bir cilt görünümüne kavuşturulur.',
                        'seo_title' => 'Sivilce İzi Kapatma Ankara | Ton Kamuflajı',
                        'seo_desc' => "Ankara'da sivilce izi kapatma ile akne sonrası kalan uygun renk farklılıklarını cilt tonunuza özel pigmentlerle kamufle edin. Randevu için hemen yazın.",
                        'intro' => "Sivilce izi kapatma, aktif akne geçtikten sonra kalan açık renkli ve yüzeysel izlerin çevre ciltle olan ton farkını azaltmaya odaklanır. Çukur ice-pick veya kabarık izlerin dokusunu doldurmaz; uygun postinflamatuvar renk farklılıklarında daha dengeli bir görünüm hedefler.\n\nStria Studio'da önce aktif lezyon bulunmadığı ve izin pigment uygulamasına elverişli olduğu kontrol edilir. Yüzün farklı bölgelerindeki renk geçişleri analiz edilerek medikal pigment hazırlanır; steril, ince uçlarla yalnızca hedef alanlara düşük yoğunlukta uygulanır ve iyileşen ton izlenir.",
                        'benefits' => [
                            'Akne sonrası açık renkli noktaların kontrastını azaltır',
                            'Yüzdeki doğal renk geçişlerine uygun mikro çalışma sağlar',
                            'Tek tek izlere hedefli pigment yerleştirilmesine olanak verir',
                            'Fondötenle yoğun bölgesel kapatma ihtiyacını hafifletebilir',
                        ],
                        'faq' => [
                            ['q' => 'Aktif sivilcenin üzerine uygulanır mı?', 'a' => 'Hayır. İltihaplı veya aktif akne bulunan cilde pigment uygulanmaz; cildin sakinleşmesi ve yüzeyin tamamen iyileşmesi beklenir.'],
                            ['q' => 'Çukur sivilce izleri kaybolur mu?', 'a' => 'Kamuflaj renk farkına yöneliktir, çukur dokuyu yükseltmez. Işığa bağlı gölgelenme sürebileceği için beklenti yüzey yapısına göre belirlenir.'],
                            ['q' => 'Yüz uygulaması kaç seans sürer?', 'a' => 'İz sayısı, dağılımı ve cildin pigmenti tutması seans sayısını etkiler. Önce sınırlı yoğunlukla çalışılır, iyileşme sonrası ihtiyaç değerlendirilir.'],
                            ['q' => 'İşlem sonrası makyaj ne zaman yapılır?', 'a' => 'Yüzey iyileşene kadar hedef bölgeye makyaj ve aktif içerikli ürün sürülmez. Size verilen bakım süresi tamamlandığında rutine kademeli dönülür.'],
                        ],
                    ],
                    [
                        'slug' => 'dovme-kapatma',
                        'gallery' => ['/images/works/dovme-kapatma-1.png', '/images/works/dovme-kapatma-2.png'],
                        'name' => 'Dövme Kapatma',
                        'desc' => 'İstenmeyen veya lazerle tam silinemeyen dövmeler cilt tonu kamuflajıyla gizlenir.',
                        'seo_title' => 'Dövme Kapatma Ankara | Cilt Tonu Kamuflajı',
                        'seo_desc' => "Ankara'da dövme kapatma ile istenmeyen veya lazer sonrası kalan uygun dövme izlerini ten rengi pigmentlerle kamufle edin. Seçenekleri görüşmek için yazın.",
                        'intro' => "Dövme kapatma, istenmeyen ya da lazer seanslarından sonra silik izi kalan küçük dövmeleri ten rengi pigmentlerle daha az görünür kılmayı amaçlayan bir alternatiftir. Mürekkebi ciltten çıkarmaz; koyu ve doygun renklerde açık pigment tek başına yeterli olmayabileceğinden uygunluk dövme bazında belirlenir.\n\nStria Studio'da dövmenin rengi, derinliği, büyüklüğü ve varsa lazer geçmişi incelenir. Gerekirse nötrleme tonlarıyla test yapılır; cilt alt tonuna göre hazırlanan medikal pigment, steril ekipmanla kademeli katmanlar hâlinde uygulanarak iyileşen renk her aşamada kontrol edilir.",
                        'benefits' => [
                            'Lazer sonrası kalan soluk mürekkep izlerinde kamuflaj seçeneği sunar',
                            'Küçük dövmelerde çevre ten rengine özel tonlama yapılır',
                            'Mürekkebin mavi, gri veya kırmızı alt tonuna göre nötrleme planlanır',
                            'Giyim ya da vücut makyajıyla kapatma ihtiyacını azaltabilir',
                        ],
                        'faq' => [
                            ['q' => 'Siyah dövme ten rengiyle tamamen kapanır mı?', 'a' => 'Yoğun siyah mürekkebin üzerine doğrudan açık pigment uygulamak doğal sonuç vermeyebilir. Solmuş, küçük veya lazerle açılmış dövmeler daha uygun olabilir.'],
                            ['q' => 'Bu uygulama lazer silmenin yerine geçer mi?', 'a' => 'Mürekkebi parçalamadığı için lazerle aynı işlem değildir. Lazer istemeyen veya lazer sonrası kalıntısı bulunan uygun adaylarda optik kamuflaj seçeneğidir.'],
                            ['q' => 'Kaç kat pigment gerekir?', 'a' => 'Dövmenin rengi ve doygunluğu katman sayısını belirler. Her katın iyileşmesi beklenir; tek seansta aşırı açık pigment yüklenmez.'],
                            ['q' => 'Bronzlaşınca kapatılan alan belli olur mu?', 'a' => 'Evet, çevre cilt bronzlaşırken pigment aynı biçimde koyulaşmaz. Renk eşleşmesinin korunması için güneşten kaçınmak ve koruyucu kullanmak gerekir.'],
                        ],
                    ],
                    [
                        'slug' => 'goz-alti-morluk-kapatma',
                        'gallery' => ['/images/works/goz-alti-morluk-kapatma-1.png', '/images/works/goz-alti-morluk-kapatma-2.png'],
                        'name' => 'Göz Altı Morluk Kapatma',
                        'desc' => 'Göz altındaki koyu halkalar cilt tonuna uyumlu pigmentlerle kalıcı olarak hafifletilir.',
                        'seo_title' => 'Göz Altı Morluk Kapatma Ankara | Aydınlık Görünüm',
                        'seo_desc' => "Ankara'da göz altı morluk kapatma ile uygun koyu halka görünümünü bölgeye özel pigment analiziyle yumuşatın. Kişisel değerlendirme için hemen bize ulaşın.",
                        'intro' => "Göz altı morluk kapatma, melanin yoğunluğu kaynaklı uygun koyu halkalarda renk kontrastını optik olarak yumuşatmayı hedefler. Damar görünümü, çöküklük veya uykusuzluk gibi farklı nedenleri ortadan kaldırmaz; ince ve hassas göz çevresinde aday seçimi özellikle önemlidir.\n\nStria Studio'da morluğun rengi, nedeni, cilt kalınlığı ve göz altı anatomisi ayrıntılı biçimde değerlendirilir. Uygun adaylarda nötrleyici medikal pigment çok küçük bir alanda test edilir; steril mikro uçlarla düşük yoğunlukta çalışılarak ani ve ağır renk yüklemesinden kaçınılır.",
                        'benefits' => [
                            'Uygun pigment kaynaklı koyu halkalarda renk kontrastını yumuşatır',
                            'Morluk tonuna göre şeftali veya nötrleyici ara renkler kullanır',
                            'İnce göz çevresi için düşük yoğunluklu hassas çalışma sunar',
                            'Günlük kapatıcı uygulamasını azaltmaya yardımcı olabilir',
                        ],
                        'faq' => [
                            ['q' => 'Her göz altı morluğu kapatılabilir mi?', 'a' => 'Hayır. Çöküklük gölgesi, belirgin damarlar, ödem veya sağlık durumları kaynaklı görünüm pigment için uygun olmayabilir; neden önce değerlendirilir.'],
                            ['q' => 'Göz çevresinde işlem güvenli midir?', 'a' => 'Bölge çok ince olduğu için yalnızca uygun adaylarda, steril ekipman ve kontrollü derinlikle çalışılır. Aktif tahriş veya göz enfeksiyonunda işlem yapılmaz.'],
                            ['q' => 'İyileşirken şişlik olur mu?', 'a' => 'Hassasiyete bağlı geçici kızarıklık veya hafif şişlik görülebilir. Bölge ovuşturulmaz ve önerilen bakım dışında ürün kullanılmaz.'],
                            ['q' => 'Sonuç neden hemen değerlendirilmez?', 'a' => 'İlk günlerde pigment ve cilt tepkisi rengi farklı gösterebilir. Gerçek ton, hassas yüzey sakinleşip pigment oturduktan sonra değerlendirilir.'],
                        ],
                    ],
                    [
                        'slug' => 'rosacea-kapatma',
                        'gallery' => ['/images/works/rosacea-kapatma-1.png', '/images/works/rosacea-kapatma-2.png'],
                        'name' => 'Rosacea Kapatma',
                        'desc' => 'Yüzdeki kalıcı kızarıklık görüntüsü medikal kamuflaj ile doğal tona yaklaştırılır.',
                        'seo_title' => 'Rosacea Kapatma Ankara | Kızarıklık Kamuflajı',
                        'seo_desc' => "Ankara'da rosacea kapatma ile stabil yüz kızarıklığının görünümünü cilt tonuna özel pigment planıyla azaltın. Uygunluk değerlendirmesi için bize yazın.",
                        'intro' => "Rosacea kapatma, yüzdeki stabil ve yüzeysel kızarıklık görünümünü renk teorisiyle dengelemeye yönelik medikal kamuflaj yaklaşımıdır. Rosaceayı tedavi etmez, alevlenmeyi durdurmaz ve aktif inflamasyon üzerinde uygulanmaz; uygun durumlarda kızıl tonun daha az belirgin görünmesi hedeflenir.\n\nStria Studio'da kızarıklığın kalıcılığı, tetikleyicileri ve cilt bariyerinin durumu incelenir. Cilt sakin ve uygun bulunduğunda nötrleme ile ten rengi pigment oranları test edilir; steril uygulama küçük alanlarda, cildin verdiği tepki sürekli izlenerek ve düşük yoğunluk korunarak gerçekleştirilir.",
                        'benefits' => [
                            'Stabil kızarıklık ile çevre ten arasındaki renk farkını yumuşatır',
                            'Kırmızı alt tonu dengelemek için kişisel nötrleme planı oluşturur',
                            'Yanak ve burun çevresinde bölgesel yoğunluğa göre çalışılır',
                            'Yeşil bazlı günlük kapatıcı ihtiyacını azaltmaya yardımcı olabilir',
                        ],
                        'faq' => [
                            ['q' => 'Rosacea alevlenmesi sırasında uygulanır mı?', 'a' => 'Hayır. Yanma, sıcaklık, kabarıklık veya aktif kızarıklık artışı varken işlem yapılmaz; cilt bariyerinin sakin ve stabil olması gerekir.'],
                            ['q' => 'Kamuflaj rosaceayı tedavi eder mi?', 'a' => 'Tedavi etmez. Yalnızca uygun ve stabil kızarıklığın görünümünü renk yoluyla azaltmayı hedefler; medikal takip gereksiniminin yerini almaz.'],
                            ['q' => 'Hassas ciltte konfor nasıl sağlanır?', 'a' => 'Küçük test alanı, düşük yoğunluk ve kısa çalışma bölümleri tercih edilir. Cilt beklenmeyen tepki verirse uygulama sürdürülmez.'],
                            ['q' => 'Kızarıklık yeniden artarsa renk uyumu bozulur mu?', 'a' => 'Alevlenme dönemlerinde doğal kızarıklık değiştiği için görünüm farklılaşabilir. Bu nedenle sonuç stabil cilt tonuna göre planlanır.'],
                        ],
                    ],
                    [
                        'slug' => 'gunes-lekesi-kapatma',
                        'gallery' => ['/images/works/gunes-lekesi-kapatma-1.png', '/images/works/gunes-lekesi-kapatma-2.png'],
                        'name' => 'Güneş Lekesi Kapatma',
                        'desc' => 'Güneşe bağlı oluşan kahverengi lekeler (solar lentigo) kalıcı olarak gizlenir.',
                        'seo_title' => 'Güneş Lekesi Kapatma Ankara | Eşit Cilt Tonu',
                        'seo_desc' => "Ankara'da güneş lekesi kapatma ile uygun solar lentigo görünümünü cilt tonunuza göre kamufle edin. Kişisel renk analizi ve randevu için hemen bize ulaşın.",
                        'intro' => "Güneş lekesi kapatma, uzun süreli UV maruziyetiyle oluşan ve dermatolojik olarak değerlendirilmiş solar lentigo alanlarında renk farkını kamufle etmeyi amaçlar. Lekenin nedenini ortadan kaldırmaz; değişen, kabaran veya tanısı kesinleşmemiş kahverengi alanlara pigment uygulanmaz.\n\nStria Studio'da lekenin öyküsü, sınırı ve güneşle renk değişimi konuşulur; gerekli uzman kontrolü doğrulandıktan sonra işlem planlanır. Çevre cildin alt tonu ölçülüp medikal pigment küçük bir noktada denenir, ardından steril ekipmanla lekenin sınırlarını sertleştirmeden ince katmanlar oluşturulur.",
                        'benefits' => [
                            'Uygun solar lentigo alanlarında koyu-açık kontrastını azaltır',
                            'Leke çevresinde keskin halka oluşturmayan geçişli çalışma sağlar',
                            'Yüz, el ve dekoltenin farklı güneşlenme düzeylerini dikkate alır',
                            'Lokal kapatıcı kullanımını azaltmaya yardımcı olabilir',
                        ],
                        'faq' => [
                            ['q' => 'Her kahverengi leke güneş lekesi midir?', 'a' => 'Hayır. Benler ve farklı cilt oluşumları benzer görünebilir. Tanısı konmamış ya da değişen bir alana kamuflajdan önce dermatolojik değerlendirme gerekir.'],
                            ['q' => 'Solar lentigo yeniden koyulaşabilir mi?', 'a' => 'UV maruziyeti çevre cildi ve doğal pigmentasyonu değiştirebilir. Kamuflaj leke oluşumunu engellemez; düzenli güneş koruması önem taşır.'],
                            ['q' => 'El üzerindeki lekelerde kalıcılık nasıldır?', 'a' => 'Eller sık yıkama, sürtünme ve güneş nedeniyle pigmenti daha hızlı açabilir. Sonucun süresi bölgeye ve bakım alışkanlıklarına göre değişir.'],
                            ['q' => 'İyileşme sırasında leke koyu görünür mü?', 'a' => 'Pigment ilk günlerde hedef tondan daha yoğun görünebilir. Yüzey yenilendikçe renk yumuşar; gerçek uyum birkaç hafta sonra kontrol edilir.'],
                        ],
                    ],
                    [
                        'slug' => 'kilcal-damar-kapatma',
                        'gallery' => ['/images/works/kilcal-damar-kapatma-1.png', '/images/works/kilcal-damar-kapatma-2.png'],
                        'name' => 'Kılcal Damar Kapatma',
                        'desc' => 'Yüz ve bacaklardaki yüzeysel kılcal damar görünümü kamufle edilerek pürüzsüz bir görünüm sağlanır.',
                        'seo_title' => 'Kılcal Damar Kapatma Ankara | Doğal Kamuflaj',
                        'seo_desc' => "Ankara'da kılcal damar kapatma ile uygun yüzeysel telenjiektazi görünümünü ten rengine özel pigmentlerle kamufle edin. Değerlendirme için bize ulaşın.",
                        'intro' => "Kılcal damar kapatma, yüz veya bacakta ince kırmızı-mor çizgiler hâlinde görülen uygun yüzeysel telenjiektazi görünümünü renk kamuflajıyla azaltmayı amaçlar. Damarı yok etmez ya da dolaşım sorununu tedavi etmez; belirgin damar yapısında önce tıbbi değerlendirme ve farklı yöntemler gerekebilir.\n\nStria Studio'da damar görünümünün derinliği, yaygınlığı ve bulunduğu bölge incelenerek pigment uygulamasına uygunluğu belirlenir. Renk teorisiyle nötrleyici ve ten tonu medikal pigmentler hazırlanır; test sonrasında steril mikro uçlarla damar çizgisini kalınlaştırmadan, çevre cilde dağılan hafif katmanlar uygulanır.",
                        'benefits' => [
                            'İnce kırmızı-mor damar çizgilerinin renk kontrastını yumuşatır',
                            'Damar tonuna göre yeşil veya sarı bazlı nötrleme planı sunar',
                            'Yüz ve bacak bölgelerinin cilt kalınlığına göre uyarlanır',
                            'Bölgesel vücut makyajı ihtiyacını azaltmaya yardımcı olabilir',
                        ],
                        'faq' => [
                            ['q' => 'Kamuflaj kılcal damarı yok eder mi?', 'a' => 'Hayır. Pigment yalnızca görünür rengi azaltmayı hedefler; damarı kapatmaz ve dolaşımla ilgili bir durumu tedavi etmez.'],
                            ['q' => 'Varisli damarlara uygulanır mı?', 'a' => 'Kabarık, ağrılı veya belirgin varisli damarlar pigment kamuflajına uygun değildir. Bu durumda öncelikle ilgili hekim değerlendirmesi gerekir.'],
                            ['q' => 'Yüzdeki damar görünümü için kaç seans gerekir?', 'a' => 'Çizgilerin yaygınlığı, rengi ve cilt hassasiyeti planı belirler. İnce ciltte düşük yoğunlukla ilerlenir ve sonuç iyileşmeden sonra değerlendirilir.'],
                            ['q' => 'İşlem sonrası kızarıklık normal midir?', 'a' => 'Geçici kızarıklık ve hassasiyet görülebilir. Bölge sürtünmeden, sıcak ortamdan ve güneşten korunur; uzayan bir tepki varsa uzman görüşü alınır.'],
                        ],
                    ],
                ],
                'related' => [],
                'gallery' => [],
            ],
        ];

        foreach ($services as $s) {
            Service::updateOrCreate(['slug' => $s['slug']], $s + [
                'is_active' => true,
                'seo_title_en' => null,
                'seo_desc_en' => null,
                'keywords_en' => null,
                'intro_en' => null,
                'aftercare_en' => null,
                'benefits_en' => null,
                'process_en' => null,
                'faq_en' => null,
            ]);
        }
    }
}
